# Generated by Django 3.2.7 on 2021-09-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_bank_clerk', models.BooleanField(default=False)),
                ('is_loan_provider', models.BooleanField(default=False)),
                ('is_loan_taker', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaxAmount', models.IntegerField()),
                ('MinAmount', models.IntegerField()),
                ('InterestRate', models.IntegerField()),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaxAmount', models.IntegerField()),
                ('MinAmount', models.IntegerField()),
                ('InterestRate', models.IntegerField()),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('NationalId', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=11)),
                ('IScore', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('NationalId', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanFundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('status', models.CharField(default='Applied', max_length=20)),
                ('LoanFund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blnkApp.loanfund')),
                ('LoanProvider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blnkApp.loanprovider')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('status', models.CharField(default='Applied', max_length=20)),
                ('Loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blnkApp.loan')),
                ('LoanTaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blnkApp.loantaker')),
            ],
        ),
    ]
