# Generated by Django 3.2.7 on 2021-09-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blnkApp', '0003_auto_20210905_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='Loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blnkApp.loan'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='LoanTaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blnkApp.loantaker'),
        ),
        migrations.AlterField(
            model_name='loanfundapplication',
            name='LoanFund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blnkApp.loanfund'),
        ),
        migrations.AlterField(
            model_name='loanfundapplication',
            name='LoanProvider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blnkApp.loanprovider'),
        ),
    ]
